### ISSUE TITLE
Warning: preg_match(): Compilation failed

### ISSUE THREAD

**Issue by Garrcomm** [smalot/pdfparser#12]
On some webservers (running PHP 5.3.3) I got the following error:
Warning: preg_match(): Compilation failed: unrecognized character after (?< at offset 9 in /data/projecten/newyork-convention/website/wingzz/library/pdfparser/vendor/smalot/pdfparser/src/Smalot/PdfParser/Element/ElementName.php on line 72

On that line, the following regex pattern exists:
/^\s_(?<name>\/[A-Z0-9._]+)(?<value>._)/si

By changing this pattern to:
/^\s_(?P<name>\/[A-Z0-9._]+)(?P<value>._)/si

the problem was solved. Named subpatterns should work correctly in PHP 5.2.2 and above, but appairently, the "old" way is still required on some 5.3.3 servers as well.

If it helps, I wrote a patch for my project, maybe it could also be imported in this project:
http://nederland.ligtin.eu/sthoolen/20130127-pdfparser-patch.txt
